export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SHORTEN_URL_REQUEST = 'SHORTEN_URL_REQUEST'
export const SHORTEN_URL_SUCCESS = 'SHORTEN_URL_SUCCESS'
export const SHORTEN_URL_FAILURE = 'SHORTEN_URL_FAILURE'

export const REDIRECT_URL_REQUEST = 'REDIRECT_URL_REQUEST'
export const REDIRECT_URL_SUCCESS = 'REDIRECT_URL_SUCCESS'
export const REDIRECT_URL_FAILURE = 'REDIRECT_URL_FAILURE'


